# Generated by Django 3.2.9 on 2022-01-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211213_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('author', 'Author'), ('contributor', 'Contributor')], max_length=128),
        ),
    ]
